/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <./utils/android_log_print.h>
#include <./common.h>
#include <./decodeNet.h>
#include <./feature.h>
#include <./gaussian.h>
#include <./hmm.h>
#include <./main.h>
#include <./net.h>
#include <./wav.h>
/* Header for class com_example_groovemax_ACR_JniUtils */

#ifndef _Included_com_example_groovemax_ACR_JniUtils
#define _Included_com_example_groovemax_ACR_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_groovemax_ACR_JniUtils
 * Method:    ACRLoadModelBuildNet
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_groovemax_ACR_JniUtils_ACRLoadModelBuildNet
(JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_groovemax_ACR_JniUtils
 * Method:    ACRWavDecode
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_groovemax_ACR_JniUtils_ACRWavDecode
        (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif

