/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <./utils/android_log_print.h>
#include <./common.h>
#include <./feature.h>
#include <./wav.h>
/* Header for class com_example_groovemax_test1_JniUtils */

#ifndef _Included_com_example_groovemax_test1_JniUtils
#define _Included_com_example_groovemax_test1_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_groovemax_test1_JniUtils
 * Method:    ACRWavDecode
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_groovemax_test1_JniUtils_ACRWavDecode
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
